<?php
require_once __DIR__ . '/../config/database.php'; require_once __DIR__ . '/../includes/functions.php'; require_admin();
$id=(int)($_GET['id']??0); $categories=$pdo->query('SELECT * FROM categories ORDER BY name')->fetchAll();
$event=['category_id'=>'','title'=>'','description'=>'','study_program'=>'Teknik Elektro','event_type'=>'offline','event_date'=>'','event_time'=>'08:00','location'=>'','quota'=>50,'poster'=>'','status'=>'open'];
if($id){$stmt=$pdo->prepare('SELECT * FROM events WHERE id=?');$stmt->execute([$id]);$event=$stmt->fetch() ?: $event;}
if($_SERVER['REQUEST_METHOD']==='POST'){
 $poster=upload_image('poster') ?: ($event['poster'] ?? null); $slug=slugify($_POST['title']).($id?'':'-'.time());
 if($id){$stmt=$pdo->prepare('UPDATE events SET category_id=?,title=?,description=?,study_program=?,event_type=?,event_date=?,event_time=?,location=?,quota=?,poster=?,status=? WHERE id=?');$stmt->execute([$_POST['category_id'],$_POST['title'],$_POST['description'],$_POST['study_program'],$_POST['event_type'],$_POST['event_date'],$_POST['event_time'],$_POST['location'],$_POST['quota'],$poster,$_POST['status'],$id]);}
 else{$stmt=$pdo->prepare('INSERT INTO events (category_id,title,slug,description,study_program,event_type,event_date,event_time,location,quota,poster,status,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)');$stmt->execute([$_POST['category_id'],$_POST['title'],$slug,$_POST['description'],$_POST['study_program'],$_POST['event_type'],$_POST['event_date'],$_POST['event_time'],$_POST['location'],$_POST['quota'],$poster,$_POST['status'],current_user()['id']]);}
 $_SESSION['flash_success']='Event berhasil disimpan.'; redirect('admin/events.php');
}
$title=$id?'Edit Event':'Tambah Event'; require_once __DIR__ . '/_layout.php';
?>
<form class="form-card" style="max-width:760px" method="post" enctype="multipart/form-data"><h1><?= e($title) ?></h1><div class="form-row"><label class="label">Judul</label><input class="input" name="title" value="<?= e($event['title']) ?>" required></div><div class="grid grid-2"><div class="form-row"><label class="label">Kategori</label><select name="category_id"><?php foreach($categories as $c): ?><option value="<?= $c['id'] ?>" <?= $event['category_id']==$c['id']?'selected':'' ?>><?= e($c['name']) ?></option><?php endforeach; ?></select></div><div class="form-row"><label class="label">Prodi</label><select name="study_program"><option <?= $event['study_program']==='Teknik Elektro'?'selected':'' ?>>Teknik Elektro</option><option <?= $event['study_program']==='Teknik Informatika'?'selected':'' ?>>Teknik Informatika</option></select></div></div><div class="form-row"><label class="label">Deskripsi</label><textarea name="description" rows="5" required><?= e($event['description']) ?></textarea></div><div class="grid grid-2"><div class="form-row"><label class="label">Tanggal</label><input class="input" type="date" name="event_date" value="<?= e($event['event_date']) ?>" required></div><div class="form-row"><label class="label">Jam</label><input class="input" type="time" name="event_time" value="<?= e(substr($event['event_time'],0,5)) ?>" required></div></div><div class="grid grid-2"><div class="form-row"><label class="label">Lokasi</label><input class="input" name="location" value="<?= e($event['location']) ?>" required></div><div class="form-row"><label class="label">Kuota</label><input class="input" type="number" name="quota" value="<?= e($event['quota']) ?>" required></div></div><div class="grid grid-2"><div class="form-row"><label class="label">Tipe</label><select name="event_type"><option>offline</option><option <?= $event['event_type']==='online'?'selected':'' ?>>online</option><option <?= $event['event_type']==='hybrid'?'selected':'' ?>>hybrid</option></select></div><div class="form-row"><label class="label">Status</label><select name="status"><option>open</option><option <?= $event['status']==='closed'?'selected':'' ?>>closed</option><option <?= $event['status']==='done'?'selected':'' ?>>done</option><option <?= $event['status']==='draft'?'selected':'' ?>>draft</option></select></div></div><div class="form-row"><label class="label">Poster</label><input class="input" type="file" name="poster" accept="image/*"></div><button class="btn btn-primary">Simpan</button></form>
<?php require_once __DIR__ . '/_footer.php'; ?>